AppBundle\Entity\Setting:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\SettingRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        multichoice:
            type: boolean
    lifecycleCallbacks: {  }
