<?php

namespace AppBundle\Repository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByNot($field, $value) {
	    $qb = $this->createQueryBuilder('a');
	    $qb->where($qb->expr()->not($qb->expr()->eq('a.'.$field, '?1')));
	    $qb->setParameter(1, $value);

	    return $qb->getQuery()
	        ->getResult();
	}
}
